export enum ClanPermission {
    CAN_MANAGE_MEMBERS = 'CAN_MANAGE_MEMBERS',
    CAN_KICK_MEMBERS = 'CAN_KICK_MEMBERS',
    CAN_EDIT_SETTINGS = 'CAN_EDIT_SETTINGS',
    CAN_CREATE_EVENTS = 'CAN_CREATE_EVENTS',
    CAN_EDIT_EVENTS = 'CAN_EDIT_EVENTS',
    CAN_DELETE_EVENTS = 'CAN_DELETE_EVENTS',
    CAN_MANAGE_SQUADS = 'CAN_MANAGE_SQUADS',
    CAN_VIEW_LOGS = 'CAN_VIEW_LOGS',
    CAN_UPLOAD_REPORTS = 'CAN_UPLOAD_REPORTS',
    MANAGE_ROLES = 'MANAGE_ROLES',
    MANUAL_PVE_EDIT = 'MANUAL_PVE_EDIT',
    CAN_EDIT_CHARACTERS = 'CAN_EDIT_CHARACTERS',
}
